### PR TITLE
fix: checking user already exist

### LINKED ISSUE #8: Bug: Checking user already exist doesn't work
Hi. Checking user already exist doesn't work.

### PR DESCRIPTION
**Pull request by awpogodin**
fixes #8

### CODE REVIEW

File: src/lib/createUser.js [hunk 1]
```diff
@@ -2,6 +2,22 @@
...
+      if (
+        name === newUser.name &&
+        email === newUser.email &&
+        signingKey === newUser.signingKey
+      ) {
+        isExist = true;
+      }
+    });
+  }
+  return isExist;
```
Comment (raccoonback) [inline src/lib/createUser.js]: @awpogodin

If the **last index** in the `users array` is `false`, it appears to return **false** unconditionally.

How about using a [`some()`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/some) `Higher-order function` rather than a `forEach()`?

```suggestion
return  users.some(({ name, email, signingKey }) =>
        name === newUser.name &&
        email === newUser.email &&
        signingKey === newUser.signingKey
    );
```

Comment (awpogodin) [reply src/lib/createUser.js]: I agree, it is preferable to use `some` here

**Comment by geongeorge** [comment]
Looks good
